SpendThriftWebsite/SpendThriftWebsite/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SpendThriftModel;
using System.Net;

namespace SpendThriftWebsite.Controllers
{
    public class ProductController : Controller
    {
        STEntities context = new STEntities();

        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Create(Product model,Category category)
        {
            if(ModelState.IsValid)
            {
                var newProduct = new Product
                                {
                                    Product_ID = model.Product_ID,
                                    Name = model.Name,
                                    Quantity = model.Quantity,
                                    Price = model.Price,
                                    Status = model.Status,
                                    Description = model.Description,
                                    ImageUrl = model.ImageUrl
                                };


                var productCategory = context.Categories.First(c => c.CategoryName == category.CategoryName);
                productCategory.Products.Add(newProduct);
                context.SaveChanges();
                return RedirectToAction("ViewProducts"); 
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        public ActionResult ViewProducts()
        {
            var allProducts = context.Products;
            return View(allProducts);
        }


        public ActionResult Edit(int productID)
        {
            var product = context.Products.FirstOrDefault(p => p.Product_ID == productID);
            return View(product);
        }

        [HttpPost]
        public ActionResult Edit(Product product)
        {
            if(ModelState.IsValid)
            {
                var existingProduct = context.Products.FirstOrDefault(p => p.Product_ID == product.Product_ID);

                existingProduct.Name = product.Name;
                existingProduct.Quantity = product.Quantity;
                existingProduct.Price = product.Price;
                existingProduct.Description = product.Description;
                existingProduct.Status = product.Status;
                existingProduct.ImageUrl = product.ImageUrl;
                context.SaveChanges();
                return RedirectToAction("ViewProducts");
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        public ActionResult Delete(int productId)
        {
            var product = context.Products.FirstOrDefault(p => p.Product_ID == productId);
            return View(product);
        }


        public ActionResult DeleteProduct(int productId)
        {
            if (ModelState.IsValid)
            {
                var categories = context.Categories;

                var productCategories = from category in categories
                                        from product in category.Products
                                        where product.Product_ID == productId
                                        select category;

                foreach (var category in productCategories)
                {
                    var product = category.Products.FirstOrDefault(p => p.Product_ID == productId);

                    if(product != null)
                    {
                        category.Products.Remove(product);
                    }                  
                }

                var reviews = context.Reviews;

                var productReviews = from review in reviews
                                    where review.ProductID == productId
                                    select review;

                foreach (var review in productReviews)
                {
                    context.Reviews.Remove(review);
                }

                var existingProduct = context.Products.FirstOrDefault(p => p.Product_ID == productId);
                context.Products.Remove(existingProduct);
                context.SaveChanges();
                return RedirectToAction("ViewProducts");
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        public ActionResult Review(int id)
        {
            var review = new Review
                            {
                                ProductID = id,
                                CustUserName = TempData["CurrentUser"].ToString(),
                                DateAdded = DateTime.Now
                            };

            TempData["CurrentUser"] = review.CustUserName;

            return View(review);
        }

        [HttpPost]
        public ActionResult Review(Review review)
        {
            if(review != null)
            {
                var customer = context.CUSTOMERs.FirstOrDefault(c => c.USERNAME == review.CustUserName);
                var product = context.Products.FirstOrDefault(p => p.Product_ID == review.ProductID);

                var newReview = new Review
                {
                    ProductID = review.ProductID,
                    CustUserName = review.CustUserName,
                    Rating = review.Rating,
                    DateAdded = review.DateAdded,
                    Description = review.Description
                };

                TempData["CurrentUser"] = newReview.CustUserName;

                context.Reviews.Add(newReview);
                context.SaveChanges();
                return RedirectToAction("Details","Store", new {id = review.ProductID});
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

        }

    }
}

SpendThriftWebsite/SpendThriftWebsite/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SpendThriftModel;
using SpendThriftWebsite.Models.ShoppingCart;
using SpendThriftWebsite.ViewModels;

namespace SpendThriftWebsite.Controllers
{
    public class ShoppingCartController : Controller
    {
        STEntities context = new STEntities();

        public ActionResult Index()
        {
            var currentCustomer = TempData["CurrentUser"].ToString();
            var cart = ShoppingCart.GetCart(this.HttpContext, currentCustomer);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };

            TempData["CurrentUser"] = currentCustomer;
            // Return the view
            return View(viewModel);
        }

        //
        // GET: /Store/AddToCart/5

        public ActionResult AddToCart(int id)
        {
            var currentCustomer = TempData["CurrentUser"].ToString();
            // Retrieve the album from the database
            var addedProduct = context.Products
                               .Single(product => product.Product_ID == id);

            var cart = ShoppingCart.GetCart(this.HttpContext, currentCustomer);

            cart.AddToCart(addedProduct);

            TempData["CurrentUser"] = currentCustomer;
            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }

        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            string currentCustomer;
            if (TempData.ContainsKey("CurrentUser"))
            {
                currentCustomer = TempData["CurrentUser"].ToString();
                var cart = ShoppingCart.GetCart(this.HttpContext, currentCustomer);
                ViewData["CartCount"] = cart.GetCount();
                TempData["CurrentUser"] = currentCustomer;
                return PartialView("CartSummary");
            }
            ViewData["CartCount"] = 0;
            return PartialView("CartSummary");
        }

    }
}

SpendThriftWebsite/SpendThriftWebsite/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SpendThriftModel;

namespace SpendThriftWebsite.Controllers
{
    public class StoreController : Controller
    {
        STEntities context = new STEntities();

        public ActionResult Index()
        {
            var categories = context.Categories.ToList();
            return View(categories);
        }

        public ActionResult Browse(string category)
        {
            var model = context.Categories.Include("Products").Single(c => c.CategoryName == category);
            return View(model);
        }

        public ActionResult Details(int id)
        {
            var model = context.Products.FirstOrDefault(p => p.Product_ID == id);
            return View(model);
        }

    }
}

SpendThriftWebsite/SpendThriftWebsite/Views/Store/Browse.cshtml
@using SpendThriftWebsite.Infrastructure

@model SpendThriftModel.Category

@{
    ViewBag.Title = "Browse";
}

<h2 class="text-info">@Model.CategoryName</h2>

<div class="row col-md-offset-1">
    @foreach (var product in Model.Products)
    {
        <div class="col-md-3 col-md-offset-0 ebayItemsDiv">
            @Html.Image(@product.ImageUrl,@product.Name)
            <h3>@Html.ActionLink("View Details", "Details", new { id = product.Product_ID })</h3>
        </div>

    }
</div>

SpendThriftWebsite/SpendThriftWebsite/Views/Store/Details.cshtml
@using SpendThriftWebsite.Infrastructure

@model SpendThriftModel.Product

@{
    ViewBag.Title = "Details";
}

<div class="row">
    <div class="col-md-3">
        @Html.Image(@Model.ImageUrl, @Model.Name)
    </div>
    <div class="col-md-6 thumbnail">
        <div class="row">
            <h2 class="text-danger col-md-4 col-md-offset-2">Price:  @Model.Price $</h2>
        </div>
        <div class="row">
            <h3 class="text-primary col-md-12 col-md-offset-2">Quantity: @Model.Quantity</h3>
        </div>      
        <div class="row">
            <h4 class="text-info col-md-12 col-md-offset-2">Description : @Model.Description</h4>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <br /><br /><br />
            <button class="btn btn-default col-md-offset-2">
                @Html.ActionLink("Add to cart", "AddToCart", "ShoppingCart", new { id = Model.Product_ID }, "")
            </button>
        </div>   
    </div>
</div>
<br />
<br />

<h2 class="text-danger">Reviews</h2>
<h2 class="btn btn-danger">@Html.ActionLink("Create New", "Review", "Product", new { id = Model.Product_ID },null)</h2>
<br />
<br />
 @foreach(var review in @Model.Reviews)
 {
    <div class="row thumbnail">
        <p class="col-md-10">@review.Description</p>
        <h4 class="text-info col-md-2 text-right">@review.CustUserName</h4>
    </div>      
 }

SpendThriftWebsite/SpendThriftWebsite/Views/Store/Index.cshtml
@model IEnumerable<SpendThriftModel.Category>

@{
    ViewBag.Title = "Index";
}

<h2 class="text-danger">Product Categories</h2>


<ul>
    @foreach (var item in Model)
    {
        <li>
            <h3 class="text-primary">@Html.ActionLink(item.CategoryName, "Browse", new { category = item.CategoryName })</h3>
        </li>
    }
</ul>